CREATE TABLE BOARD (	
    "BOARD_NO" NUMBER, 
	"BOARD_TITLE" VARCHAR2(50), 
	"BOARD_WRITER" VARCHAR2(15), 
	"BOARD_CONTENT" VARCHAR2(2000), 
	"BOARD_ORIGINAL_FILENAME" VARCHAR2(100), 
	"BOARD_RENAMED_FILENAME" VARCHAR2(100), 
	"BOARD_DATE" DATE DEFAULT SYSDATE, 
	"BOARD_READCOUNT" NUMBER DEFAULT 0, 
    CONSTRAINT PK_BOARD_NO PRIMARY KEY(BOARD_NO),
    CONSTRAINT FK_BOARD_WRITER FOREIGN KEY(BOARD_WRITER) REFERENCES MEMBER(USERID) ON DELETE SET NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글번호';
COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글제목';
COMMENT ON COLUMN "BOARD"."BOARD_WRITER" IS '게시글작성자 아이디';
COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글내용';
COMMENT ON COLUMN "BOARD"."BOARD_ORIGINAL_FILENAME" IS '첨부파일원래이름';
COMMENT ON COLUMN "BOARD"."BOARD_RENAMED_FILENAME" IS '첨부파일변경이름';
COMMENT ON COLUMN "BOARD"."BOARD_DATE" IS '게시글올린날짜';
COMMENT ON COLUMN "BOARD"."BOARD_READCOUNT" IS '조회수';

--게시판시퀀스생성
CREATE SEQUENCE SEQ_BOARD_NO
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;
SELECT * FROM BOARD;