SELECT * FROM MEMBER;
SELECT * FROM HOST;
DELETE FROM MEMBER WHERE MEMBER_ID='testtest';
DELETE FROM MEMBER WHERE MEMBER_ID='aksenwpdhkd';
SELECT * FROM CLASS;
SELECT COUNT(MEMBER_ID) FROM COUPON WHERE MEMBER_ID='test';
SELECT * FROM COUPON;
SELECT * FROM COUPON_TYPE;

SELECT * FROM NOTICE;
SELECT * FROM NOTICE_IMAGE;
DELETE FROM NOTICE_IMAGE;
DELETE FROM NOTICE;
SELECT * FROM CALC;
ALTER TABLE HOST MODIFY CALC_REQ_DATE NUMBER DEFAULT 1;